Feature/31599 sync fork
evoila/helm-wrapper pull request #16
Opened 2023-05-24 11:32 UTC by christiangebhard

2023-05-24 13:24 UTC, niksteph requested changes

2023-05-24 13:24 UTC, niksteph commented on helm.go
>  	"k8s.io/cli-runtime/pkg/genericclioptions"
```suggestion
	"helm.sh/helm/v3/pkg/kube"
        "helm.sh/helm/v3/pkg/registry"
	"k8s.io/cli-runtime/pkg/genericclioptions"
```

2023-05-24 13:27 UTC, christiangebhard commented on helm.go
>  	"k8s.io/cli-runtime/pkg/genericclioptions"
This is a bug in Github, the indentation is the same for all lines, I tried to fix it with a little trick

2023-05-24 13:51 UTC, niksteph approved these changes

2023-05-25 09:06 UTC, Cryptel117 approved these changes

2023-05-25 10:17 UTC, miriSch commented on Dockerfile
In the original repository, they replaced CMD with ENTRYPOINT. Is there a reason not to do this?

2023-05-26 05:33 UTC, miriSch approved these changes

2023-05-26 07:06 UTC, merged